resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.2.8
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.1.500"
  CakeVersion: "0.30.0"
  NuGetVersion: '4.7.1'
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)

# Mac job seems to hang with unit tests currently, needs more testing (also need a mac)
#   - template: pipeline/cake-job.yml@rsg
#     parameters:
#       name: 'macOS'
#       dependsOn: GitVersion
#       vmImage: "macOS-10.13"
#       pushNuget: false
#       Configuration: $(Configuration)
#       Verbosity: $(Verbosity)
#       CakeVersion: $(CakeVersion)
#       DotNetVersion: $(DotNetVersion)
#       NuGetVersion: $(NuGetVersion)
#       Script: build.cake

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'Linux'
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      CakeVersion: $(CakeVersion)
      DotNetVersion: $(DotNetVersion)
      NuGetVersion: $(NuGetVersion)
      Script: build.cake

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "VS2017-Win2016"
      pushNuget: true
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      CakeVersion: $(CakeVersion)
      DotNetVersion: $(DotNetVersion)
      NuGetVersion: $(NuGetVersion)
      Script: build.cake
